/*
 * siteProject
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateTodoDto model module.
 * @module model/CreateTodoDto
 * @version 1.0
 */
export default class CreateTodoDto {
  /**
   * Constructs a new <code>CreateTodoDto</code>.
   * @alias module:model/CreateTodoDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateTodoDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateTodoDto} obj Optional instance to populate.
   * @return {module:model/CreateTodoDto} The populated <code>CreateTodoDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateTodoDto();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('isDone'))
        obj.isDone = ApiClient.convertToType(data['isDone'], 'Boolean');
      if (data.hasOwnProperty('ownerId'))
        obj.ownerId = ApiClient.convertToType(data['ownerId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
CreateTodoDto.prototype.title = undefined;

/**
 * @member {String} description
 */
CreateTodoDto.prototype.description = undefined;

/**
 * @member {Boolean} isDone
 */
CreateTodoDto.prototype.isDone = undefined;

/**
 * @member {String} ownerId
 */
CreateTodoDto.prototype.ownerId = undefined;

